### ISSUE TITLE
open for offering screen

### ISSUE THREAD

**Issue by yoncayunatci** [selinfildis/CS353-Group1-Project#5]
sanırım register house ekranından ayrı olarak evleri offeringe açmak için ekrana ihtiyacımız var.

- register house ekranındaki price'ı silip offering screen'e eklememiz lazım
- start date ve end date olmalı

- offeringteki bir eve rezervasyon yapıldığında offeringteki date intervalı yenilenmeli. Onu söyle düşünmüştük mesela 1 ocakla 31 ocak arası bir ev offeringte. 5 ocak 8 ocak arası rezervasyon yapıldıysa bir tuple 1 ocak 5 ocak arasını tutar, diğer aralık içi de bir tane tuple daha ekleyebiliriz.

**Comment by yoncayunatci** [comment]
manage house ekranından open for offering ekranına geçiş için offering ekleme butonu gerekli

**Comment by selinfildis** [comment]
ya onu modalla yapabiliriz manage house sayfasında unutmuşum, tenks ^^

**Comment by selinfildis** [comment]
hallettik bi şekilde
